import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'te';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    smartGrama: 'Smart Grama',
    tagline: 'Digitally Connecting Citizens & Panchayat',
    home: 'Home',
    reportIssue: 'Report Issue',
    tree: 'Tree',
    water: 'Water',
    solar: 'Solar',
    schemes: 'Schemes',
    myRequests: 'My Requests',
    adminDashboard: 'Admin Dashboard',
    login: 'Login',
    logout: 'Logout',
    loggingIn: 'Logging in...',
    contactInfo: 'Contact Information',
    panchayatOffice: 'Panchayat Office',
    address: 'Village Road, District, State - 123456',
    phone: 'Phone',
    quickLinks: 'Quick Links',
    aboutSmartGrama: 'About Smart Grama',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    disclaimer: 'Disclaimer',
    disclaimerText: 'This is an official government platform. All information submitted is subject to verification.',
    allRightsReserved: 'All rights reserved',
    builtWith: 'Built with',
    using: 'using',
    welcomeToSmartGrama: 'Welcome to Smart Grama!',
    setupProfileMessage: 'Please set up your profile to continue',
    fullName: 'Full Name',
    enterYourName: 'Enter your name',
    mobileNumber: 'Mobile Number',
    enterMobileNumber: 'Enter mobile number',
    continue: 'Continue',
    saving: 'Saving...',
    nameRequired: 'Name is required',
    profileSaved: 'Profile saved successfully',
    profileSaveError: 'Failed to save profile',
    authRequired: 'Authentication Required',
    pleaseLoginToContinue: 'Please login to continue',
    accessDenied: 'Access Denied',
    adminAccessRequired: 'Admin access required',
    loading: 'Loading...',
    submitComplaint: 'Submit Complaint',
    complaintCategory: 'Category',
    selectCategory: 'Select category',
    garbage: 'Garbage',
    streetLight: 'Street Light',
    drainage: 'Drainage',
    others: 'Others',
    description: 'Description',
    describeIssue: 'Describe the issue',
    uploadPhoto: 'Upload Photo',
    uploadAudio: 'Upload Audio (Optional)',
    location: 'Location',
    autoDetected: 'Auto-detected',
    submit: 'Submit',
    submitting: 'Submitting...',
    complaintSubmitted: 'Complaint submitted successfully',
    complaintSubmitError: 'Failed to submit complaint',
    requestTree: 'Request Tree Plantation',
    treeType: 'Tree Type',
    selectTreeType: 'Select tree type',
    neem: 'Neem',
    mango: 'Mango',
    teak: 'Teak',
    banyan: 'Banyan',
    peepal: 'Peepal',
    uploadPlantingPhoto: 'Upload Planting Photo (Optional)',
    treeRequested: 'Tree request submitted successfully',
    treeRequestError: 'Failed to submit tree request',
    requestWaterProject: 'Request Rainwater Harvesting',
    houseDetails: 'House Details',
    ownerName: 'Owner Name',
    plotSize: 'Plot Size (sq ft)',
    uploadLandPhoto: 'Upload Land Photo',
    waterProjectRequested: 'Water project request submitted successfully',
    waterProjectError: 'Failed to submit water project request',
    applySolarScheme: 'Apply for Solar Scheme',
    solarSchemeInfo: 'PM Surya Ghar Muft Bijli Yojana',
    uploadAadhaar: 'Upload Aadhaar Document',
    uploadElectricityBill: 'Upload Electricity Bill',
    uploadHousePhoto: 'Upload House Photo',
    solarApplicationSubmitted: 'Solar application submitted successfully',
    solarApplicationError: 'Failed to submit solar application',
    myComplaintsTitle: 'My Complaints',
    myTreesTitle: 'My Tree Requests',
    myWaterProjectsTitle: 'My Water Projects',
    mySolarApplicationsTitle: 'My Solar Applications',
    noComplaints: 'No complaints submitted yet',
    noTrees: 'No tree requests submitted yet',
    noWaterProjects: 'No water projects submitted yet',
    noSolarApplications: 'No solar applications submitted yet',
    submittedOn: 'Submitted on',
    assignedWorker: 'Assigned Worker',
    rateWork: 'Rate Work',
    rating: 'Rating',
    submitRating: 'Submit Rating',
    ratingSubmitted: 'Rating submitted successfully',
    ratingError: 'Failed to submit rating',
    governmentSchemes: 'Government Schemes',
    schemeDetails: 'Scheme Details',
    eligibility: 'Eligibility',
    benefits: 'Benefits',
    applicationProcess: 'Application Process',
    requiredDocuments: 'Required Documents',
    contactDetails: 'Contact Details',
    officialWebsite: 'Official Website',
    visitWebsite: 'Visit Website',
    backToSchemes: 'Back to Schemes',
    aboutTitle: 'About Smart Grama',
    aboutContent: 'Smart Grama is a digital platform connecting citizens with their Panchayat for sustainable development.',
    privacyPolicyTitle: 'Privacy Policy',
    termsTitle: 'Terms of Service',
    dashboardTitle: 'Admin Dashboard',
    complaintsManagement: 'Complaints Management',
    treeManagement: 'Tree Management',
    waterProjectsManagement: 'Water Projects Management',
    solarManagement: 'Solar Management',
    totalComplaints: 'Total Complaints',
    completionRate: 'Completion Rate',
    treeSurvivalRate: 'Tree Survival Rate',
    solarInstallations: 'Solar Installations',
    waterProjects: 'Water Projects',
    recentActivity: 'Recent Activity',
    filterByCategory: 'Filter by Category',
    allCategories: 'All Categories',
    updateStatus: 'Update Status',
    assignWorker: 'Assign Worker',
    workerName: 'Worker Name',
    uploadCompletionProof: 'Upload Completion Proof',
    statusUpdated: 'Status updated successfully',
    statusUpdateError: 'Failed to update status',
    totalTrees: 'Total Trees',
    survivingTrees: 'Surviving Trees',
    survivalStatus: 'Survival Status',
    surviving: 'Surviving',
    dead: 'Dead',
    survivalStatusUpdated: 'Survival status updated successfully',
    survivalStatusError: 'Failed to update survival status',
    totalProjects: 'Total Projects',
    completedProjects: 'Completed Projects',
    projectStatusUpdated: 'Project status updated successfully',
    projectStatusError: 'Failed to update project status',
    totalApplications: 'Total Applications',
    installedHomes: 'Installed Homes',
    estimatedCO2Reduction: 'Estimated CO₂ Reduction',
    estimatedEnergyGeneration: 'Estimated Energy Generation',
    tonsPerYear: 'tons/year',
    kWhPerYear: 'kWh/year',
    viewDocuments: 'View Documents',
    aadhaarDocument: 'Aadhaar Document',
    electricityBill: 'Electricity Bill',
    housePhoto: 'House Photo',
    applicationStatusUpdated: 'Application status updated successfully',
    applicationStatusError: 'Failed to update application status',
  },
  te: {
    smartGrama: 'స్మార్ట్ గ్రామ',
    tagline: 'పౌరులు & పంచాయతీని డిజిటల్‌గా కనెక్ట్ చేయడం',
    home: 'హోమ్',
    reportIssue: 'సమస్య నివేదించండి',
    tree: 'చెట్టు',
    water: 'నీరు',
    solar: 'సౌర',
    schemes: 'పథకాలు',
    myRequests: 'నా అభ్యర్థనలు',
    adminDashboard: 'అడ్మిన్ డాష్‌బోర్డ్',
    login: 'లాగిన్',
    logout: 'లాగౌట్',
    loggingIn: 'లాగిన్ అవుతోంది...',
    contactInfo: 'సంప్రదింపు సమాచారం',
    panchayatOffice: 'పంచాయతీ కార్యాలయం',
    address: 'గ్రామ రోడ్డు, జిల్లా, రాష్ట్రం - 123456',
    phone: 'ఫోన్',
    quickLinks: 'త్వరిత లింక్‌లు',
    aboutSmartGrama: 'స్మార్ట్ గ్రామ గురించి',
    privacyPolicy: 'గోప్యతా విధానం',
    termsOfService: 'సేవా నిబంధనలు',
    disclaimer: 'నిరాకరణ',
    disclaimerText: 'ఇది అధికారిక ప్రభుత్వ వేదిక. సమర్పించిన అన్ని సమాచారం ధృవీకరణకు లోబడి ఉంటుంది.',
    allRightsReserved: 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి',
    builtWith: 'తయారు చేయబడింది',
    using: 'ఉపయోగించి',
    welcomeToSmartGrama: 'స్మార్ట్ గ్రామకు స్వాగతం!',
    setupProfileMessage: 'కొనసాగించడానికి దయచేసి మీ ప్రొఫైల్‌ను సెటప్ చేయండి',
    fullName: 'పూర్తి పేరు',
    enterYourName: 'మీ పేరు నమోదు చేయండి',
    mobileNumber: 'మొబైల్ నంబర్',
    enterMobileNumber: 'మొబైల్ నంబర్ నమోదు చేయండి',
    continue: 'కొనసాగించు',
    saving: 'సేవ్ చేస్తోంది...',
    nameRequired: 'పేరు అవసరం',
    profileSaved: 'ప్రొఫైల్ విజయవంతంగా సేవ్ చేయబడింది',
    profileSaveError: 'ప్రొఫైల్ సేవ్ చేయడంలో విఫలమైంది',
    authRequired: 'ప్రామాణీకరణ అవసరం',
    pleaseLoginToContinue: 'కొనసాగించడానికి దయచేసి లాగిన్ చేయండి',
    accessDenied: 'యాక్సెస్ నిరాకరించబడింది',
    adminAccessRequired: 'అడ్మిన్ యాక్సెస్ అవసరం',
    loading: 'లోడ్ అవుతోంది...',
    submitComplaint: 'ఫిర్యాదు సమర్పించండి',
    complaintCategory: 'వర్గం',
    selectCategory: 'వర్గాన్ని ఎంచుకోండి',
    garbage: 'చెత్త',
    streetLight: 'వీధి దీపం',
    drainage: 'డ్రైనేజీ',
    others: 'ఇతరులు',
    description: 'వివరణ',
    describeIssue: 'సమస్యను వివరించండి',
    uploadPhoto: 'ఫోటో అప్‌లోడ్ చేయండి',
    uploadAudio: 'ఆడియో అప్‌లోడ్ చేయండి (ఐచ్ఛికం)',
    location: 'స్థానం',
    autoDetected: 'స్వయంచాలకంగా గుర్తించబడింది',
    submit: 'సమర్పించు',
    submitting: 'సమర్పిస్తోంది...',
    complaintSubmitted: 'ఫిర్యాదు విజయవంతంగా సమర్పించబడింది',
    complaintSubmitError: 'ఫిర్యాదు సమర్పించడంలో విఫలమైంది',
    requestTree: 'చెట్టు నాటడం అభ్యర్థించండి',
    treeType: 'చెట్టు రకం',
    selectTreeType: 'చెట్టు రకాన్ని ఎంచుకోండి',
    neem: 'వేప',
    mango: 'మామిడి',
    teak: 'టేకు',
    banyan: 'మర్రి',
    peepal: 'రావి',
    uploadPlantingPhoto: 'నాటడం ఫోటో అప్‌లోడ్ చేయండి (ఐచ్ఛికం)',
    treeRequested: 'చెట్టు అభ్యర్థన విజయవంతంగా సమర్పించబడింది',
    treeRequestError: 'చెట్టు అభ్యర్థన సమర్పించడంలో విఫలమైంది',
    requestWaterProject: 'వర్షపు నీటి సేకరణ అభ్యర్థించండి',
    houseDetails: 'ఇంటి వివరాలు',
    ownerName: 'యజమాని పేరు',
    plotSize: 'ప్లాట్ పరిమాణం (చ.అ)',
    uploadLandPhoto: 'భూమి ఫోటో అప్‌లోడ్ చేయండి',
    waterProjectRequested: 'నీటి ప్రాజెక్ట్ అభ్యర్థన విజయవంతంగా సమర్పించబడింది',
    waterProjectError: 'నీటి ప్రాజెక్ట్ అభ్యర్థన సమర్పించడంలో విఫలమైంది',
    applySolarScheme: 'సౌర పథకం కోసం దరఖాస్తు చేయండి',
    solarSchemeInfo: 'PM సూర్య ఘర్ ముఫ్త్ బిజ్లీ యోజన',
    uploadAadhaar: 'ఆధార్ పత్రం అప్‌లోడ్ చేయండి',
    uploadElectricityBill: 'విద్యుత్ బిల్లు అప్‌లోడ్ చేయండి',
    uploadHousePhoto: 'ఇంటి ఫోటో అప్‌లోడ్ చేయండి',
    solarApplicationSubmitted: 'సౌర దరఖాస్తు విజయవంతంగా సమర్పించబడింది',
    solarApplicationError: 'సౌర దరఖాస్తు సమర్పించడంలో విఫలమైంది',
    myComplaintsTitle: 'నా ఫిర్యాదులు',
    myTreesTitle: 'నా చెట్టు అభ్యర్థనలు',
    myWaterProjectsTitle: 'నా నీటి ప్రాజెక్టులు',
    mySolarApplicationsTitle: 'నా సౌర దరఖాస్తులు',
    noComplaints: 'ఇంకా ఫిర్యాదులు సమర్పించబడలేదు',
    noTrees: 'ఇంకా చెట్టు అభ్యర్థనలు సమర్పించబడలేదు',
    noWaterProjects: 'ఇంకా నీటి ప్రాజెక్టులు సమర్పించబడలేదు',
    noSolarApplications: 'ఇంకా సౌర దరఖాస్తులు సమర్పించబడలేదు',
    submittedOn: 'సమర్పించిన తేదీ',
    assignedWorker: 'కేటాయించిన కార్మికుడు',
    rateWork: 'పనిని రేట్ చేయండి',
    rating: 'రేటింగ్',
    submitRating: 'రేటింగ్ సమర్పించండి',
    ratingSubmitted: 'రేటింగ్ విజయవంతంగా సమర్పించబడింది',
    ratingError: 'రేటింగ్ సమర్పించడంలో విఫలమైంది',
    governmentSchemes: 'ప్రభుత్వ పథకాలు',
    schemeDetails: 'పథకం వివరాలు',
    eligibility: 'అర్హత',
    benefits: 'ప్రయోజనాలు',
    applicationProcess: 'దరఖాస్తు ప్రక్రియ',
    requiredDocuments: 'అవసరమైన పత్రాలు',
    contactDetails: 'సంప్రదింపు వివరాలు',
    officialWebsite: 'అధికారిక వెబ్‌సైట్',
    visitWebsite: 'వెబ్‌సైట్‌ను సందర్శించండి',
    backToSchemes: 'పథకాలకు తిరిగి వెళ్ళండి',
    aboutTitle: 'స్మార్ట్ గ్రామ గురించి',
    aboutContent: 'స్మార్ట్ గ్రామ అనేది స్థిరమైన అభివృద్ధి కోసం పౌరులను వారి పంచాయతీతో కనెక్ట్ చేసే డిజిటల్ వేదిక.',
    privacyPolicyTitle: 'గోప్యతా విధానం',
    termsTitle: 'సేవా నిబంధనలు',
    dashboardTitle: 'అడ్మిన్ డాష్‌బోర్డ్',
    complaintsManagement: 'ఫిర్యాదుల నిర్వహణ',
    treeManagement: 'చెట్ల నిర్వహణ',
    waterProjectsManagement: 'నీటి ప్రాజెక్టుల నిర్వహణ',
    solarManagement: 'సౌర నిర్వహణ',
    totalComplaints: 'మొత్తం ఫిర్యాదులు',
    completionRate: 'పూర్తి రేటు',
    treeSurvivalRate: 'చెట్టు మనుగడ రేటు',
    solarInstallations: 'సౌర సంస్థాపనలు',
    waterProjects: 'నీటి ప్రాజెక్టులు',
    recentActivity: 'ఇటీవలి కార్యాచరణ',
    filterByCategory: 'వర్గం ద్వారా ఫిల్టర్ చేయండి',
    allCategories: 'అన్ని వర్గాలు',
    updateStatus: 'స్థితిని నవీకరించండి',
    assignWorker: 'కార్మికుడిని కేటాయించండి',
    workerName: 'కార్మికుడి పేరు',
    uploadCompletionProof: 'పూర్తి రుజువు అప్‌లోడ్ చేయండి',
    statusUpdated: 'స్థితి విజయవంతంగా నవీకరించబడింది',
    statusUpdateError: 'స్థితిని నవీకరించడంలో విఫలమైంది',
    totalTrees: 'మొత్తం చెట్లు',
    survivingTrees: 'మనుగడలో ఉన్న చెట్లు',
    survivalStatus: 'మనుగడ స్థితి',
    surviving: 'మనుగడలో ఉంది',
    dead: 'చనిపోయింది',
    survivalStatusUpdated: 'మనుగడ స్థితి విజయవంతంగా నవీకరించబడింది',
    survivalStatusError: 'మనుగడ స్థితిని నవీకరించడంలో విఫలమైంది',
    totalProjects: 'మొత్తం ప్రాజెక్టులు',
    completedProjects: 'పూర్తయిన ప్రాజెక్టులు',
    projectStatusUpdated: 'ప్రాజెక్ట్ స్థితి విజయవంతంగా నవీకరించబడింది',
    projectStatusError: 'ప్రాజెక్ట్ స్థితిని నవీకరించడంలో విఫలమైంది',
    totalApplications: 'మొత్తం దరఖాస్తులు',
    installedHomes: 'సంస్థాపించిన ఇళ్ళు',
    estimatedCO2Reduction: 'అంచనా CO₂ తగ్గింపు',
    estimatedEnergyGeneration: 'అంచనా శక్తి ఉత్పత్తి',
    tonsPerYear: 'టన్నులు/సంవత్సరం',
    kWhPerYear: 'kWh/సంవత్సరం',
    viewDocuments: 'పత్రాలను చూడండి',
    aadhaarDocument: 'ఆధార్ పత్రం',
    electricityBill: 'విద్యుత్ బిల్లు',
    housePhoto: 'ఇంటి ఫోటో',
    applicationStatusUpdated: 'దరఖాస్తు స్థితి విజయవంతంగా నవీకరించబడింది',
    applicationStatusError: 'దరఖాస్తు స్థితిని నవీకరించడంలో విఫలమైంది',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
