/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Category = IDL.Variant({
  'streetLight' : IDL.Null,
  'drainage' : IDL.Null,
  'garbage' : IDL.Null,
  'others' : IDL.Null,
});
export const Complaint = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'completionProof' : IDL.Opt(ExternalBlob),
  'audio' : IDL.Opt(ExternalBlob),
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'assignedWorker' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Opt(IDL.Nat),
  'mobile' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
});
export const SolarApplication = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'housePhoto' : ExternalBlob,
  'userId' : IDL.Text,
  'createdAt' : Time,
  'billDoc' : ExternalBlob,
  'aadhaarDoc' : ExternalBlob,
});
export const Tree = IDL.Record({
  'id' : IDL.Text,
  'treeType' : IDL.Text,
  'userId' : IDL.Text,
  'survivalStatus' : IDL.Bool,
  'photo' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
  'plantedDate' : Time,
});
export const WaterProject = IDL.Record({
  'id' : IDL.Text,
  'completionStatus' : Status,
  'userId' : IDL.Text,
  'createdAt' : Time,
  'workerAssigned' : IDL.Opt(IDL.Text),
  'landPhoto' : ExternalBlob,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'mobile' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComplaintRating' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getAllSolarApplications' : IDL.Func(
      [],
      [IDL.Vec(SolarApplication)],
      ['query'],
    ),
  'getAllTrees' : IDL.Func([], [IDL.Vec(Tree)], ['query']),
  'getAllWaterProjects' : IDL.Func([], [IDL.Vec(WaterProject)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaint' : IDL.Func([IDL.Text], [Complaint], ['query']),
  'getMyComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getMySolarApplications' : IDL.Func(
      [],
      [IDL.Vec(SolarApplication)],
      ['query'],
    ),
  'getMyTrees' : IDL.Func([], [IDL.Vec(Tree)], ['query']),
  'getMyWaterProjects' : IDL.Func([], [IDL.Vec(WaterProject)], ['query']),
  'getSolarApplication' : IDL.Func([IDL.Text], [SolarApplication], ['query']),
  'getTree' : IDL.Func([IDL.Text], [Tree], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWaterProject' : IDL.Func([IDL.Text], [WaterProject], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestTree' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Text],
      [IDL.Text],
      [],
    ),
  'requestWaterProject' : IDL.Func([ExternalBlob], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitComplaint' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'submitSolarApplication' : IDL.Func(
      [ExternalBlob, ExternalBlob, ExternalBlob],
      [IDL.Text],
      [],
    ),
  'updateComplaintStatus' : IDL.Func(
      [IDL.Text, Status, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateSolarApplicationStatus' : IDL.Func([IDL.Text, Status], [], []),
  'updateTreeStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateWaterProjectStatus' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), Status],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'streetLight' : IDL.Null,
    'drainage' : IDL.Null,
    'garbage' : IDL.Null,
    'others' : IDL.Null,
  });
  const Complaint = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'completionProof' : IDL.Opt(ExternalBlob),
    'audio' : IDL.Opt(ExternalBlob),
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'assignedWorker' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Opt(IDL.Nat),
    'mobile' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
  });
  const SolarApplication = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'housePhoto' : ExternalBlob,
    'userId' : IDL.Text,
    'createdAt' : Time,
    'billDoc' : ExternalBlob,
    'aadhaarDoc' : ExternalBlob,
  });
  const Tree = IDL.Record({
    'id' : IDL.Text,
    'treeType' : IDL.Text,
    'userId' : IDL.Text,
    'survivalStatus' : IDL.Bool,
    'photo' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
    'plantedDate' : Time,
  });
  const WaterProject = IDL.Record({
    'id' : IDL.Text,
    'completionStatus' : Status,
    'userId' : IDL.Text,
    'createdAt' : Time,
    'workerAssigned' : IDL.Opt(IDL.Text),
    'landPhoto' : ExternalBlob,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'mobile' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComplaintRating' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getAllSolarApplications' : IDL.Func(
        [],
        [IDL.Vec(SolarApplication)],
        ['query'],
      ),
    'getAllTrees' : IDL.Func([], [IDL.Vec(Tree)], ['query']),
    'getAllWaterProjects' : IDL.Func([], [IDL.Vec(WaterProject)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaint' : IDL.Func([IDL.Text], [Complaint], ['query']),
    'getMyComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getMySolarApplications' : IDL.Func(
        [],
        [IDL.Vec(SolarApplication)],
        ['query'],
      ),
    'getMyTrees' : IDL.Func([], [IDL.Vec(Tree)], ['query']),
    'getMyWaterProjects' : IDL.Func([], [IDL.Vec(WaterProject)], ['query']),
    'getSolarApplication' : IDL.Func([IDL.Text], [SolarApplication], ['query']),
    'getTree' : IDL.Func([IDL.Text], [Tree], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWaterProject' : IDL.Func([IDL.Text], [WaterProject], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestTree' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Text],
        [IDL.Text],
        [],
      ),
    'requestWaterProject' : IDL.Func([ExternalBlob], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitComplaint' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'submitSolarApplication' : IDL.Func(
        [ExternalBlob, ExternalBlob, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'updateComplaintStatus' : IDL.Func(
        [IDL.Text, Status, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateSolarApplicationStatus' : IDL.Func([IDL.Text, Status], [], []),
    'updateTreeStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateWaterProjectStatus' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), Status],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };