/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'streetLight' : null } |
  { 'drainage' : null } |
  { 'garbage' : null } |
  { 'others' : null };
export interface Complaint {
  'id' : string,
  'status' : Status,
  'completionProof' : [] | [ExternalBlob],
  'audio' : [] | [ExternalBlob],
  'userId' : string,
  'name' : string,
  'createdAt' : Time,
  'assignedWorker' : [] | [string],
  'description' : string,
  'category' : Category,
  'rating' : [] | [bigint],
  'mobile' : string,
  'photo' : [] | [ExternalBlob],
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface SolarApplication {
  'id' : string,
  'status' : Status,
  'housePhoto' : ExternalBlob,
  'userId' : string,
  'createdAt' : Time,
  'billDoc' : ExternalBlob,
  'aadhaarDoc' : ExternalBlob,
}
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface Tree {
  'id' : string,
  'treeType' : string,
  'userId' : string,
  'survivalStatus' : boolean,
  'photo' : [] | [ExternalBlob],
  'location' : string,
  'plantedDate' : Time,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'mobile' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WaterProject {
  'id' : string,
  'completionStatus' : Status,
  'userId' : string,
  'createdAt' : Time,
  'workerAssigned' : [] | [string],
  'landPhoto' : ExternalBlob,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComplaintRating' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getAllSolarApplications' : ActorMethod<[], Array<SolarApplication>>,
  'getAllTrees' : ActorMethod<[], Array<Tree>>,
  'getAllWaterProjects' : ActorMethod<[], Array<WaterProject>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaint' : ActorMethod<[string], Complaint>,
  'getMyComplaints' : ActorMethod<[], Array<Complaint>>,
  'getMySolarApplications' : ActorMethod<[], Array<SolarApplication>>,
  'getMyTrees' : ActorMethod<[], Array<Tree>>,
  'getMyWaterProjects' : ActorMethod<[], Array<WaterProject>>,
  'getSolarApplication' : ActorMethod<[string], SolarApplication>,
  'getTree' : ActorMethod<[string], Tree>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWaterProject' : ActorMethod<[string], WaterProject>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestTree' : ActorMethod<[string, [] | [ExternalBlob], string], string>,
  'requestWaterProject' : ActorMethod<[ExternalBlob], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitComplaint' : ActorMethod<
    [
      string,
      string,
      Category,
      string,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      string,
    ],
    string
  >,
  'submitSolarApplication' : ActorMethod<
    [ExternalBlob, ExternalBlob, ExternalBlob],
    string
  >,
  'updateComplaintStatus' : ActorMethod<
    [string, Status, [] | [string]],
    undefined
  >,
  'updateSolarApplicationStatus' : ActorMethod<[string, Status], undefined>,
  'updateTreeStatus' : ActorMethod<[string, boolean], undefined>,
  'updateWaterProjectStatus' : ActorMethod<
    [string, [] | [string], Status],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];