/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Tree {
    id: string;
    treeType: string;
    userId: string;
    survivalStatus: boolean;
    photo?: ExternalBlob;
    location: string;
    plantedDate: Time;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Complaint {
    id: string;
    status: Status;
    completionProof?: ExternalBlob;
    audio?: ExternalBlob;
    userId: string;
    name: string;
    createdAt: Time;
    assignedWorker?: string;
    description: string;
    category: Category;
    rating?: bigint;
    mobile: string;
    photo?: ExternalBlob;
    location: string;
}
export interface SolarApplication {
    id: string;
    status: Status;
    housePhoto: ExternalBlob;
    userId: string;
    createdAt: Time;
    billDoc: ExternalBlob;
    aadhaarDoc: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface WaterProject {
    id: string;
    completionStatus: Status;
    userId: string;
    createdAt: Time;
    workerAssigned?: string;
    landPhoto: ExternalBlob;
}
export interface UserProfile {
    name: string;
    role: string;
    mobile?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    streetLight = "streetLight",
    drainage = "drainage",
    garbage = "garbage",
    others = "others"
}
export enum Status {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComplaintRating(id: string, rating: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllComplaints(): Promise<Array<Complaint>>;
    getAllSolarApplications(): Promise<Array<SolarApplication>>;
    getAllTrees(): Promise<Array<Tree>>;
    getAllWaterProjects(): Promise<Array<WaterProject>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComplaint(id: string): Promise<Complaint>;
    getMyComplaints(): Promise<Array<Complaint>>;
    getMySolarApplications(): Promise<Array<SolarApplication>>;
    getMyTrees(): Promise<Array<Tree>>;
    getMyWaterProjects(): Promise<Array<WaterProject>>;
    getSolarApplication(id: string): Promise<SolarApplication>;
    getTree(id: string): Promise<Tree>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWaterProject(id: string): Promise<WaterProject>;
    isCallerAdmin(): Promise<boolean>;
    requestTree(treeType: string, photo: ExternalBlob | null, location: string): Promise<string>;
    requestWaterProject(landPhoto: ExternalBlob): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitComplaint(name: string, mobile: string, category: Category, description: string, photo: ExternalBlob | null, audio: ExternalBlob | null, location: string): Promise<string>;
    submitSolarApplication(aadhaarDoc: ExternalBlob, billDoc: ExternalBlob, housePhoto: ExternalBlob): Promise<string>;
    updateComplaintStatus(id: string, status: Status, assignedWorker: string | null): Promise<void>;
    updateSolarApplicationStatus(id: string, status: Status): Promise<void>;
    updateTreeStatus(id: string, survivalStatus: boolean): Promise<void>;
    updateWaterProjectStatus(id: string, workerAssigned: string | null, status: Status): Promise<void>;
}
import type { Category as _Category, Complaint as _Complaint, ExternalBlob as _ExternalBlob, SolarApplication as _SolarApplication, Status as _Status, Time as _Time, Tree as _Tree, UserProfile as _UserProfile, UserRole as _UserRole, WaterProject as _WaterProject, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComplaintRating(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComplaintRating(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComplaintRating(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComplaints();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComplaints();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSolarApplications(): Promise<Array<SolarApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSolarApplications();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSolarApplications();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrees(): Promise<Array<Tree>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrees();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrees();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWaterProjects(): Promise<Array<WaterProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWaterProjects();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWaterProjects();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaint(arg0: string): Promise<Complaint> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaint(arg0);
                return from_candid_Complaint_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaint(arg0);
            return from_candid_Complaint_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyComplaints();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyComplaints();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySolarApplications(): Promise<Array<SolarApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySolarApplications();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySolarApplications();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTrees(): Promise<Array<Tree>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTrees();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTrees();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWaterProjects(): Promise<Array<WaterProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWaterProjects();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWaterProjects();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSolarApplication(arg0: string): Promise<SolarApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.getSolarApplication(arg0);
                return from_candid_SolarApplication_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSolarApplication(arg0);
            return from_candid_SolarApplication_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTree(arg0: string): Promise<Tree> {
        if (this.processError) {
            try {
                const result = await this.actor.getTree(arg0);
                return from_candid_Tree_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTree(arg0);
            return from_candid_Tree_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaterProject(arg0: string): Promise<WaterProject> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaterProject(arg0);
                return from_candid_WaterProject_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaterProject(arg0);
            return from_candid_WaterProject_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async requestTree(arg0: string, arg1: ExternalBlob | null, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestTree(arg0, await to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestTree(arg0, await to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async requestWaterProject(arg0: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWaterProject(await to_candid_ExternalBlob_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWaterProject(await to_candid_ExternalBlob_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitComplaint(arg0: string, arg1: string, arg2: Category, arg3: string, arg4: ExternalBlob | null, arg5: ExternalBlob | null, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitComplaint(arg0, arg1, to_candid_Category_n38(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_opt_n34(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n34(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitComplaint(arg0, arg1, to_candid_Category_n38(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_opt_n34(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n34(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async submitSolarApplication(arg0: ExternalBlob, arg1: ExternalBlob, arg2: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSolarApplication(await to_candid_ExternalBlob_n35(this._uploadFile, this._downloadFile, arg0), await to_candid_ExternalBlob_n35(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n35(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSolarApplication(await to_candid_ExternalBlob_n35(this._uploadFile, this._downloadFile, arg0), await to_candid_ExternalBlob_n35(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n35(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateComplaintStatus(arg0: string, arg1: Status, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaintStatus(arg0, to_candid_Status_n40(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaintStatus(arg0, to_candid_Status_n40(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateSolarApplicationStatus(arg0: string, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSolarApplicationStatus(arg0, to_candid_Status_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSolarApplicationStatus(arg0, to_candid_Status_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTreeStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTreeStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTreeStatus(arg0, arg1);
            return result;
        }
    }
    async updateWaterProjectStatus(arg0: string, arg1: string | null, arg2: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWaterProjectStatus(arg0, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg1), to_candid_Status_n40(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWaterProjectStatus(arg0, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg1), to_candid_Status_n40(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_Category_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_Complaint_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Complaint): Promise<Complaint> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_SolarApplication_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SolarApplication): Promise<SolarApplication> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_Tree_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tree): Promise<Tree> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_WaterProject_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WaterProject): Promise<WaterProject> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    completionProof: [] | [_ExternalBlob];
    audio: [] | [_ExternalBlob];
    userId: string;
    name: string;
    createdAt: _Time;
    assignedWorker: [] | [string];
    description: string;
    category: _Category;
    rating: [] | [bigint];
    mobile: string;
    photo: [] | [_ExternalBlob];
    location: string;
}): Promise<{
    id: string;
    status: Status;
    completionProof?: ExternalBlob;
    audio?: ExternalBlob;
    userId: string;
    name: string;
    createdAt: Time;
    assignedWorker?: string;
    description: string;
    category: Category;
    rating?: bigint;
    mobile: string;
    photo?: ExternalBlob;
    location: string;
}> {
    return {
        id: value.id,
        status: from_candid_Status_n13(_uploadFile, _downloadFile, value.status),
        completionProof: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.completionProof)),
        audio: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.audio)),
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        assignedWorker: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.assignedWorker)),
        description: value.description,
        category: from_candid_Category_n18(_uploadFile, _downloadFile, value.category),
        rating: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.rating)),
        mobile: value.mobile,
        photo: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.photo)),
        location: value.location
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    housePhoto: _ExternalBlob;
    userId: string;
    createdAt: _Time;
    billDoc: _ExternalBlob;
    aadhaarDoc: _ExternalBlob;
}): Promise<{
    id: string;
    status: Status;
    housePhoto: ExternalBlob;
    userId: string;
    createdAt: Time;
    billDoc: ExternalBlob;
    aadhaarDoc: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_Status_n13(_uploadFile, _downloadFile, value.status),
        housePhoto: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.housePhoto),
        userId: value.userId,
        createdAt: value.createdAt,
        billDoc: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.billDoc),
        aadhaarDoc: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.aadhaarDoc)
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    treeType: string;
    userId: string;
    survivalStatus: boolean;
    photo: [] | [_ExternalBlob];
    location: string;
    plantedDate: _Time;
}): Promise<{
    id: string;
    treeType: string;
    userId: string;
    survivalStatus: boolean;
    photo?: ExternalBlob;
    location: string;
    plantedDate: Time;
}> {
    return {
        id: value.id,
        treeType: value.treeType,
        userId: value.userId,
        survivalStatus: value.survivalStatus,
        photo: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.photo)),
        location: value.location,
        plantedDate: value.plantedDate
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    completionStatus: _Status;
    userId: string;
    createdAt: _Time;
    workerAssigned: [] | [string];
    landPhoto: _ExternalBlob;
}): Promise<{
    id: string;
    completionStatus: Status;
    userId: string;
    createdAt: Time;
    workerAssigned?: string;
    landPhoto: ExternalBlob;
}> {
    return {
        id: value.id,
        completionStatus: from_candid_Status_n13(_uploadFile, _downloadFile, value.completionStatus),
        userId: value.userId,
        createdAt: value.createdAt,
        workerAssigned: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.workerAssigned)),
        landPhoto: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.landPhoto)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    mobile: [] | [string];
}): {
    name: string;
    role: string;
    mobile?: string;
} {
    return {
        name: value.name,
        role: value.role,
        mobile: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.mobile))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): Status {
    return "pending" in value ? Status.pending : "completed" in value ? Status.completed : "inProgress" in value ? Status.inProgress : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    streetLight: null;
} | {
    drainage: null;
} | {
    garbage: null;
} | {
    others: null;
}): Category {
    return "streetLight" in value ? Category.streetLight : "drainage" in value ? Category.drainage : "garbage" in value ? Category.garbage : "others" in value ? Category.others : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Complaint>): Promise<Array<Complaint>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Complaint_n11(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SolarApplication>): Promise<Array<SolarApplication>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SolarApplication_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tree>): Promise<Array<Tree>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Tree_n24(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WaterProject>): Promise<Array<WaterProject>> {
    return await Promise.all(value.map(async (x)=>await from_candid_WaterProject_n27(_uploadFile, _downloadFile, x)));
}
function to_candid_Category_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Status_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    mobile?: string;
}): {
    name: string;
    role: string;
    mobile: [] | [string];
} {
    return {
        name: value.name,
        role: value.role,
        mobile: value.mobile ? candid_some(value.mobile) : candid_none()
    };
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    streetLight: null;
} | {
    drainage: null;
} | {
    garbage: null;
} | {
    others: null;
} {
    return value == Category.streetLight ? {
        streetLight: null
    } : value == Category.drainage ? {
        drainage: null
    } : value == Category.garbage ? {
        garbage: null
    } : value == Category.others ? {
        others: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == Status.pending ? {
        pending: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
